Traceback (most recent call last):
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\site-packages\nbclient\client.py", line 608, in async_setup_kernel
    yield
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\schatzm\Anaconda3\envs\ju-book\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load the path containing all the functions to use DISpANALYSIS
from sys import path
path.append('../DISpANALYSIS/')
from analysis_execution import compute_diagnosis
import numpy as np
import pandas as pd
from data_classification_labels import create_combination
from graphics import scatterplot_decrease_parameters, plot_pcurve_by_measure, composed_plot
from table_of_results import table_of_results
from exponential_fit import decission_data_exponential
from load_morphology_data import morphoparam
# Avoid warnings
import warnings
warnings.filterwarnings('ignore')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 4[0m
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01msys[39;00m [38;5;28;01mimport[39;00m path
[0;32m      3[0m path[38;5;241m.[39mappend([38;5;124m'[39m[38;5;124m../DISpANALYSIS/[39m[38;5;124m'[39m)
[1;32m----> 4[0m [38;5;28;01mfrom[39;00m [38;5;21;01manalysis_execution[39;00m [38;5;28;01mimport[39;00m compute_diagnosis
[0;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m

[1;31mModuleNotFoundError[0m: No module named 'analysis_execution'
ModuleNotFoundError: No module named 'analysis_execution'

